apiVersion: v1
kind: ConfigMap
metadata:
  name: stocks-configmap
  namespace: stocks
data:
  DB_NAME: "dt_stocks"
  SRVURL: "stocks-server-svc:80"
  NUMLOOPS: "100"
  CREATESTOCKS: "100"
  INITSTOCKS: "10000"
  MAXSTOCKS: "100000"
  HARDWORK_INTENSITY: "10"
  DBSRV: "postgres-svc"
  DBPORT: "5432"
  APP_NAME: "Stock Management"
  SVC_SUFFIX: "azure"
  SECURITY_CONTEXT: "Stocks"
  COST_CENTER: "StockExchange"
  COST_PRODUCT: "Stocks"
  GIT_REPO: "https://github.com/ihudak/dt-generator-stocks-server-python/"
  LOG_DEST: "screen" # screen or file
  CRASH_SIM: "40"
