kind: Namespace
apiVersion: v1
metadata:
  name: stocks
  annotations:
    metadata.dynatrace.com/boo: Stocks
    metadata.dynatrace.com/my.annotation: custom_cost_center
    metadata.dynatrace.com/dt.cost.costcenter: fixed_cost_center
    metadata.dynatrace.com/dt.security_circle: mgd.live.pm
    metadata.dynatrace.com/dt.management_zone: stockmarket.mgd
    metadata.dynatrace.com/dt.owner_team: mgd-pm
    metadata.dynatrace.com/dt.owner: alex
    mystuff/my.annotation: FinDept
  labels:
    name: stocks
    mystuff/my.label: Prod
